### ISSUE TITLE
Paid theme

### ISSUE THREAD

**Issue by TyeWillCode** [Hyricon-Dev/Faliactyl#2]
This theme is a paid theme, u do not have the right to redistribute this. I will contact the owners and take this immediatly.

**Comment by acktarcodes** [comment]
Didnt see you talking about this when rian was about to redistribute it. Talking about contacting owners, you are the guy that fixed the stylesheet links in reliactyl. Wasnt a paid theme then was it

**Comment by TyeWillCode** [comment]
I did not fix the style themes. I was fixing script in there, i did not touch the theme. I fixed arico
